[preview]
max_width  = 1000
max_height = 2000

[opener]
tdf = [{ run = 'tdf %s -f', desc = "Open pdf with tdf.", block = true }]

sioyek = [{ run = 'sioyek %s', desc = "Open pdf with sioyek.", orphan = true }]

[open]
prepend_rules = [{ url = "*.pdf", use = ["tdf", "sioyek"] }]

[plugin]
prepend_previewers = [
  # Directory previewer
  { url = "*/", run = 'piper -- eza -TL=2 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
  # Notebook previewer
  { url = "*.ipynb", run = 'piper -- nbpreview --no-paging --nerd-font --decorated --no-files --unicode --color --color-system=standard --theme=ansi_dark "$1"' },
  # { url = "*.ipynb", run = "nbpreview" },
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/vnd.rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  { mime = "application/x-zstd", run = "ouch" },
  { mime = "application/zstd", run = "ouch" },
  { mime = "application/java-archive", run = "ouch" },
]
